# Generated by Django 3.0.2 on 2020-01-03 11:45

import datetime
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filled', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Times',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_start', models.TimeField(choices=[(datetime.time(9, 0), '9AM'), (datetime.time(10, 0), '10AM'), (datetime.time(11, 0), '11AM')])),
                ('date_start', models.DateField()),
                ('time_end', models.DateTimeField(editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user', models.Model),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='times',
            constraint=models.UniqueConstraint(fields=('time_start', 'date_start'), name='unique_datetime'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='appointment_app.User'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='times',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='times', to='appointment_app.Times'),
        ),
    ]
